name: Challenge-1

on: push

jobs:
    job1:
        name: First Job
        runs-on: ubuntu-latest
        steps:
        - name: Checkout on Linux
          uses: actions/checkout@v2
        - name: Get Date
          run: date
    job2:
        name: Second Job
        runs-on: windows-latest
        steps:
        - name: Checkout on Windows
          uses: actions/checkout@v2
        - name: Get Date
          run: Get-Date
    job3:
        name: Third Job
        runs-on: macos-latest
        steps:
        - name: Checkout on MacOS
          uses: actions/checkout@v2
        - name: Get Date
          run: date
    job4:
        needs: [job1, job2, job3]
        name: Fourth Job
        runs-on: macos-14
        steps:
        - name: Checkout on MacOS-M1
          uses: actions/checkout@v2
        - name: Get Date
          run: date
             
