name: Artifact

on: [push]

env:
  FILE_NAME: artifact

jobs:
  job1:
    name: main
    runs-on: ubuntu-latest
    steps:

    - name: Check out Code
      uses: actions/checkout@v2

    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ${{ env.FILE_NAME }}
        path: ./${{ env.FILE_NAME }}.txt
  